### ISSUE TITLE
add properties, setters & getters

### ISSUE THREAD

**Issue by iampersistent** [vespolina/core#68]
add properties, setters & getters to BillingAgreement & setters and getters BillingAgreementInterface
- $processRequestOffset (string)
  processRequestOffset is the amount of time from the billedToDate to when an BillingRequest should be processed. 
- $generateRequestOffset (string)
  generateRequestOffset is the amount of time from the processRequestOffset to when the BillingRequest is generated, will always be <=0
- $generateRequestOn (DateTime)

The accepted strings for the offset will be in the php datetime format http://www.php.net/manual/en/datetime.formats.php

methods should be fluent

**Comment by jcroll** [comment]
@iampersistent  Ok I am checking if there is a way to make sure the string is in datetime format here: http://stackoverflow.com/questions/15709493/is-there-anyway-in-php-to-enforce-a-string-to-be-in-the-datetime-format

Otherwise I will just put it in the docblocks.

Unless of course you know of a way...

**Comment by iampersistent** [comment]
well there is a response there now and its a pretty straight forward process to check it, so go for that solution.

**Comment by jcroll** [comment]
I believe this can be closed.

**Comment by inspiran** [comment]
thx!
